version: '3.7'
services:
  dashboard_backend:
    build:
      context: .
      dockerfile: dockerfile
    image: dashboard_backend:latest
    container_name: dashboard_backend
    volumes:
      - ./backend/:/home/backend/
    ports:
      - 8080:80
    working_dir: /home/backend/
    stdin_open: true
    tty: true
    # command: bash -c "./celery.sh"
    # command: bash -c "python manage.py runserver 0.0.0.0:80"

  redis:
    image: redis:latest
    container_name: project3_redis
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    container_name: dashboard_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd!
      - MYSQL_DATABASE=main
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=user1
      - TZ=Asia/Taipei
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql/
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
